packages:
  - bash-completion
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - python3-pip
  - virtualenv
  - python3-setuptools
  - elinks
  - etcd-client
  - nfs-common

K8s_packages:
  - kubelet={{ K8s.version }}
  - kubeadm={{ K8s.version }}
  - kubectl={{ K8s.version }}
